version: "3.8"

services:
  postgresdb:
    image: sasidharssan/cric_attacks_db:latest
    env_file: "./db_variables.env"
    ports:
      - "5432:5432"
    
  cric-attacks:
    image: sasidharssan/cric_attacks:latest
    env_file: "./db_variables.env"
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
